### ISSUE TITLE
Preserve CDATA sections, don't convert them to generic Text nodes

### ISSUE THREAD

**Issue by mbeckerle** [scala/scala-xml#74]
This issue migrated from https://issues.scala-lang.org/browse/SI-3368. (Note: It is not closed there.)

There is substantial discussion there which is not reproduced here. Please see that tracker.

The original description: 

Sort of defeats part of the purpose of using a CDATA...

```
scala> <hi><![CDATA[This & That]]></hi>
res0: scala.xml.Elem = <hi>This &amp; That</hi>
```

**Comment by mbeckerle** [comment]
This issue was already fixed back prior to the spin-off of scala-xml to github.

See the original issue https://issues.scala-lang.org/browse/SI-3368

**Comment by ploddi** [comment]
Can someone elaborate on status of this? Seems like issue still here event `scala-xml` moved to separate module.

**Comment by ploddi** [comment]
Is this still depends on compiler flag? Can it be altered by `factory.setFeature` on parser level?
